In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [8]:
iris=datasets.load_iris()
iris_data=iris.data
iris_label=iris.target
xtrain,xtest,ytrain,ytest=train_test_split(iris_data,iris_label)
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(xtrain,ytrain)
y_pred=classifier.predict(xtest)
print('confusion matrix')
print(confusion_matrix(ytest,y_pred))
print('accuracy')
print(classification_report(ytest,y_pred))


confusion matrix
[[16  0  0]
 [ 0 11  0]
 [ 0  1 10]]
accuracy
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.92      1.00      0.96        11
          2       1.00      0.91      0.95        11

avg / total       0.98      0.97      0.97        38



In [ ]:
n